### ISSUE TITLE
maybe add a "auto be silent" posibility

### ISSUE THREAD

**Issue by andlo** [domcross/mycroft-chat-skill#8]
As a regular user of mattermost skill I do get anoyied when mycroft keeps disturbing me with anounsing how many unread messages there is on mattermost. Well not during the daytime when it is super to be notised if something is going on. But at eveaning and night time.....

I dont remember to stop monitoring and when i do iforget to activate it againg.

So what I were thinking were either a settings for "night time" so he stops monitoring (or only anounses personal messaages or mentiones) or that he stops anounsing if there is more than X messages. 

I dont know, but do know that it anois me when I am going to sleep, and he loud and clear says "there is X unread messages on mattermost".

**Comment by domcross** [comment]
Thought about this a bit. Simplest solution for you would be to use the [Naptime-Skill](https://github.com/mycroftai/skill-naptime/), this will mute audio output of all skills until Mycroft gets awoken by user command. Before going to sleep you only have to remember to tell Mycroft "go to sleep"...

**Comment by andlo** [comment]
Yah you are right. That is a optoion. But I dont remember to go to every room in the house and activate naptime ;) and even worse I dont remember to wake him up again ;)
